edition = "2021"
fn_params_layout = "Tall"
hard_tabs = false
match_block_trailing_comma = true
max_width = 110
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
tab_spaces = 4
use_field_init_shorthand = true
use_small_heuristics = "Default"
