[package]
name = "passport-tg-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
log = "0.4"
serde = "1"
serde_json = "1"
teloxide = { version = "0.13", features = ["macros"] }
tokio = { version = "1.8", features = ["rt-multi-thread", "macros"] }
