[package]
name = "passport-tg-rs"
version = "0.1.0"
edition = "2021"
default-run = "announcer"
publish = false

[lib]
name = "passport_tg"
path = "src/lib.rs"

[[bin]]
name = "announcer"
path = "src/announcer/bin/main.rs"

[[bin]]
name = "sofia"
path = "src/sofia/bin/main.rs"

[dependencies]
anyhow = "1.0.91"
axum = "0.7.7"
chrono = { version = "0.4", features = ["serde"] }
dotenv = "0.15"
indoc = "2"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.8.2", features = ["postgres", "runtime-tokio", "tls-rustls", "chrono"] }
teloxide = { version = "0.13", features = ["macros"] }
thiserror = "1.0.65"
tokio = { version = "1.8", features = ["rt-multi-thread", "macros"] }
tower-http = { version = "0.6.1", features = ["cors"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
url = "2.5"
